### ISSUE TITLE
ActionSheet on Android Crashes

### ISSUE THREAD

**Issue by vbisbest** [aritchie/acr-xamarin-forms#92]
Using emulator on API level 19.   After the ActionSheet is shown, app crashes.

Code:
            Acr.UserDialogs.ActionSheetConfig asc = new ActionSheetConfig();
            asc.Add("Edit");
            asc.Add("Delete");
            asc.Add("MineChat");
            asc.SetCancel();

            UserDialogs.Instance.ActionSheet(asc);

Dump:
[Mono] Assembly Ref addref Acr.UserDialogs[0xb8eccd20] -> System.Core[0xb8faa540]: 6
[WindowManager] 
[WindowManager] android.view.WindowLeaked: Activity minefriendsandroid.FriendsActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{b27301c0 V.E..... R.....I. 0,0-684,324} that was originally added here
[WindowManager] 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:348)
[WindowManager] 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
[WindowManager] 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
[WindowManager] 	at android.app.Dialog.show(Dialog.java:286)
[WindowManager] 	at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
[WindowManager] 	at mono.android.widget.AdapterView_OnItemClickListenerImplementor.n_onItemClick(Native Method)
[WindowManager] 	at mono.android.widget.AdapterView_OnItemClickListenerImplementor.onItemClick(AdapterView_OnItemClickListenerImplementor.java:29)
[WindowManager] 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
[WindowManager] 	at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
[WindowManager] 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2904)
[WindowManager] 	at android.widget.AbsListView$3.run(AbsListView.java:3638)
[WindowManager] 	at android.os.Handler.handleCallback(Handler.java:733)
[WindowManager] 	at android.os.Handler.dispatchMessage(Handler.java:95)
[WindowManager] 	at android.os.Looper.loop(Looper.java:136)
[WindowManager] 	at android.app.ActivityThread.main(ActivityThread.java:5017)
[WindowManager] 	at java.lang.reflect.Method.invokeNative(Native Method)
[WindowManager] 	at java.lang.reflect.Method.invoke(Method.java:515)
[WindowManager] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
[WindowManager] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
[WindowManager] 	at dalvik.system.NativeStart.main(Native Method)
[Choreographer] Skipped 31 frames!  The application may be doing too much work on its main thread.

**Comment by vbisbest** [comment]
Sorry, this was user error.  Closing case.
